#
# This is the default remote configuration file for uberAgent
#
# On Linux, this file must be located in /etc/uberAgent. Make sure to save changes to this file as uberAgent-remote-config-Linux.conf.
# uberAgent-remote-config-Linux.conf serves as the configuration file for central configuration management.

#
# Documentation: https://docs.citrix.com/en-us/uberagent/current-release/installation/central-config-file-management/
#

############################################
#
# Central configuration management
#
# Configurable settings in this section:
#
#   Setting name: ConfigFilePath
#   Description: The path to the configuration archive on a remote source. This should be a path to a mounted SMB share.
#   Valid values: Any valid path (quotes may be used, but are not necessary)
#   Default: empty
#   Required: yes
#
############################################

[RemoteConfiguration]
