name: Configuration

on:
  push:
    branches:
      - "version/7.3"
    paths-ignore:
      - "config-dist/**" # avoid recursion
  pull_request:
    branches:
      - "version/7.3"
    paths-ignore:
      - "config-dist/**" # avoid recursion

env:
  SOURCE_DIR_PATH: config/
  TARGET_DIR_PATH: config-dist/
  TARGET_FILE: uberAgent.uAConfig

jobs:
  build-archive:
    name: Build
    # Add "id-token" with the intended permissions.
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Validate uberAgent.conf <> uberAgent-data-volume-optimized.conf"
        run: |
          CONFIG_CHANGED="$(git diff --name-only config/uberAgent.conf)"
          CONFIG_OPTIMIZED_CHANGED="$(git diff --name-only config/uberAgent-data-volume-optimized.conf)"
          if ( [ -n "${CONFIG_CHANGED}" ] && [ -z "${CONFIG_OPTIMIZED_CHANGED}" ] ) || ( [ -z "${CONFIG_CHANGED}" ] && [ -n "${CONFIG_OPTIMIZED_CHANGED}" ] )
          then
            echo "Changes must be applied uberAgent.conf and uberAgent-data-volume-optimized.conf, too."
            exit 1
          fi
          echo "Changes are in sync."
          exit 0
        continue-on-error: false

      - name: Create uberAgent.uAConfig archive file
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          directory: "${{ env.SOURCE_DIR_PATH }}"
          filename: "${{ env.TARGET_FILE }}"

      - name: Upload uberAgent.uAConfig
        uses: actions/upload-artifact@v4
        with:
          name: ConfigArchive
          path: "${{ env.SOURCE_DIR_PATH }}${{ env.TARGET_FILE }}"
          if-no-files-found: error
          retention-days: 1

  # Publishing is limited to actual push events.
  push-archive:
    if: ${{ github.event_name == 'push' }}
    name: Push
    runs-on: ubuntu-latest
    needs: [build-archive]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.VLSVC_PAT }}

      - uses: actions/download-artifact@v4
        with:
          name: ConfigArchive
          path: ${{ env.TARGET_DIR_PATH }}

      - name: Commit archive
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Updated config archive
          commit_user_name: vastlimits
          commit_user_email: devops@vastlimits.com
